#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Any;

our %SPEC;

$SPEC{list_dists} = {
    v => 1.1,
    summary => 'List installed Perl distributions',
    args => {
    },
};
sub list_dists {
    require Dist::Util;

    my %args = @_;

    [200, "OK", [Dist::Util::list_dists()]];
}

Perinci::CmdLine::Any->new(
    url => "/main/list_dists",
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % list-dists


=head1 DESCRIPTION

=cut
