#!perl

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

# AUTHORITY
# DATE
# DIST
# VERSION

our %SPEC;

$SPEC{list_dists} = {
    v => 1.1,
    summary => 'List installed Perl distributions',
    args => {
        detail => {
            schema => 'bool*',
            cmdline_aliases => {l=>{}},
        },
    },
};
sub list_dists {
    require Dist::Util;

    my %args = @_;

    [200, "OK", [Dist::Util::list_dists(%args)]];
}

Perinci::CmdLine::Any->new(
    url => "/main/list_dists",
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % list-dists


=head1 DESCRIPTION

=cut
